# This file was generated by GoReleaser. DO NOT EDIT.
cask "cache-detective" do
  version "0.0.1"

  on_macos do
    sha256 "6c076ca1d4cdae2a90dcf1f804350b2d2a78cba4766b21c12ed64fd70c39ef39"
    url "https://github.com/cerberauth/cache-detective/releases/download/v#{version}/cache-detective_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "043d2a5c15e2e08868f5163ddb782f580ab9bd1b12e52157c3d078d0374008e9"
      url "https://github.com/cerberauth/cache-detective/releases/download/v#{version}/cache-detective_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "85908fe7dd212546fdfed16bff2accd46d29af5ef4a269b99e664a7b79374125"
      url "https://github.com/cerberauth/cache-detective/releases/download/v#{version}/cache-detective_Linux_x86_64.tar.gz"
    end
  end

  name "cache-detective"
  desc "HTTP cache & CDN behavior analysis CLI - cacheability, live cache state, CDN fingerprinting, and cache poisoning/deception checks."
  homepage "https://github.com/cerberauth/cache-detective"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cache-detective"

  # No zap stanza required
end
