# This file was generated by GoReleaser. DO NOT EDIT.
cask "cache-detective" do
  version "0.1.0"

  on_macos do
    sha256 "191203d6bfaf358e7a018ecf805a48d86eae55bb444586aa0dd41e7f52e1649d"
    url "https://github.com/cerberauth/cache-detective/releases/download/v#{version}/cache-detective_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "8c665f53ee793652d49c7e5a8a22c22908bb6d63224ba0f69cbbfafdae7a73d2"
      url "https://github.com/cerberauth/cache-detective/releases/download/v#{version}/cache-detective_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f68db77188c5d006df31936fb6bb8a4bd871ecddbfb999e4327e7c72f92d273"
      url "https://github.com/cerberauth/cache-detective/releases/download/v#{version}/cache-detective_Linux_x86_64.tar.gz"
    end
  end

  name "cache-detective"
  desc "HTTP cache & CDN behavior analysis CLI - cacheability, live cache state, CDN fingerprinting, and cache poisoning/deception checks."
  homepage "https://github.com/cerberauth/cache-detective"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cache-detective"

  # No zap stanza required
end
