# This file was generated by GoReleaser. DO NOT EDIT.
cask "iamigrate" do
  version "0.1.0"

  on_macos do
    sha256 "d8421cb460a331466b66b0fab5c2c2b939abd57fe0d6540aee1404e50491cf93"
    url "https://github.com/cerberauth/iamigrate/releases/download/v#{version}/iamigrate_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "d3648f0fa0e38fb0cfe199258428628996b7e97801e29bf22b7ca30744afb90b"
      url "https://github.com/cerberauth/iamigrate/releases/download/v#{version}/iamigrate_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9fdd400e48688dbf223749bf50c0e0e36d7be488a9991c555c9eec71168db47a"
      url "https://github.com/cerberauth/iamigrate/releases/download/v#{version}/iamigrate_Linux_x86_64.tar.gz"
    end
  end

  name "iamigrate"
  desc "CIAM identity migration toolkit — export, map, validate, and import users into Auth0."
  homepage "https://github.com/cerberauth/iamigrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iamigrate"

  # No zap stanza required
end
