# This file was generated by GoReleaser. DO NOT EDIT.
cask "iamigrate" do
  version "0.1.0"

  on_macos do
    sha256 "3fd6a7a3892b621dbe500d5007163a0ed60d0970def9c5b6c68ce73628f2d550"
    url "https://github.com/cerberauth/iamigrate/releases/download/v#{version}/iamigrate_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "97e5feab27be7008b627f6c4d6c00b1f92702189ef5863c91d4b1ade71664bed"
      url "https://github.com/cerberauth/iamigrate/releases/download/v#{version}/iamigrate_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "342804a5c1094fcb37ce077058fda12858d174b68c016728f3f5771c5873ee7a"
      url "https://github.com/cerberauth/iamigrate/releases/download/v#{version}/iamigrate_Linux_x86_64.tar.gz"
    end
  end

  name "iamigrate"
  desc "CIAM identity migration toolkit — export, map, validate, and import users into Auth0."
  homepage "https://github.com/cerberauth/iamigrate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iamigrate"

  # No zap stanza required
end
