# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwtop" do
  name "jwtop"
  desc "JWT operations CLI - decode, verify, create, sign, and exploit JWTs."
  homepage "https://github.com/cerberauth/jwtop"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jwtop"

  on_macos do
    url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Darwin_all.tar.gz"
    sha256 "46f2895bda8a41f6c75fc7b6322b9c0877903e316b6cdca3bc7eedee291be862"
  end

  on_linux do
    on_intel do
      url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Linux_x86_64.tar.gz"
      sha256 "4932750cb8f41c872ce6de03deb9d229ad4ae74501f2bc32a960aa789dd5fb74"
    end
    on_arm do
      url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Linux_arm64.tar.gz"
      sha256 "b9afc4a11e87a9af31fcaad173f020348ab3a59a98da63949c33bbd4326d78ea"
    end
  end

  # No zap stanza required
end
