# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwtop" do
  version "0.8.0"

  on_macos do
    sha256 "805b0e6eeeff13a4664f68b4ab9acd4c3a74acc23ccd78d84622b4cda4eee923"
    url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "0e4da0d954306016f33b71e4d27de02549f20103211ae56102bc979b1f64771a"
      url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e41226955e3c3c696076196545badcc1f97ba55a2ffdacef764e538b3e94cc7e"
      url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Linux_x86_64.tar.gz"
    end
  end

  name "jwtop"
  desc "JWT operations CLI - decode, verify, create, sign, and exploit JWTs."
  homepage "https://github.com/cerberauth/jwtop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jwtop"

  # No zap stanza required
end
