# This file was generated by GoReleaser. DO NOT EDIT.
cask "jwtop" do
  version "0.4.0"

  on_macos do
    sha256 "b4943b58766d63f98d11d06c8b53394666ddb269e2404d8a07878dd22ee68204"
    url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "d5bee384c2ca7fdfd8a9e6e56adc440d0c21ca78e4e71bc86577aaa3a1eb49b7"
      url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e9d7eb65a16bc3e2b8b9ef1160e22688aac376520464e57c28c0870f756fcf15"
      url "https://github.com/cerberauth/jwtop/releases/download/v#{version}/jwtop_Linux_arm64.tar.gz"
    end
  end

  name "jwtop"
  desc "JWT operations CLI - decode, verify, create, sign, and exploit JWTs."
  homepage "https://github.com/cerberauth/jwtop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jwtop"

  # No zap stanza required

end
