# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-oathkeeper" do
  version "0.8.0"

  on_macos do
    sha256 "c2c1e213e8d5772b47a5b8ab3166da6b3aa5b199ff7b5d998b53120cf9922f01"
    url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "b4d24735c98edad3947a82805e84d52e600799cc960eb22ebb5d0f995cec3769"
      url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89b39a0ef388dcb6733cd6c42c05bf20256f4176818df5801341ddd1ab8ec9a0"
      url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Linux_x86_64.tar.gz"
    end
  end

  name "openapi-oathkeeper"
  desc "Generate Ory Oathkeeper access rules from an OpenAPI 3 contract."
  homepage "https://github.com/cerberauth/openapi-oathkeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-oathkeeper"

  # No zap stanza required
end
