# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-oathkeeper" do
  version "0.7.17"

  on_macos do
    sha256 "c2d6a82d3f08cd84c72dbec536352b4dc38441066780738c3a48b61f6b6f1104"
    url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "cdba857c1ebfe919f7342d5dc8aabdebee612aa37742919f4a2472857cc4767e"
      url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b560caacdeb568d1eab9da5e13278fa3a0d2c289d032447694b0ec72ec20c973"
      url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Linux_arm64.tar.gz"
    end
  end

  name "openapi-oathkeeper"
  desc "Generate Ory Oathkeeper access rules from an OpenAPI 3 contract."
  homepage "https://github.com/cerberauth/openapi-oathkeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-oathkeeper"

  # No zap stanza required

end
