# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-oathkeeper" do
  version "0.7.17"

  on_macos do
    sha256 "03c3be5d65be175b1fc8397b8ace4d316e1e8fed3971ced1762777fac829c98c"
    url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Darwin_all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "a3673fffb7e390e9d90b5e00354016e7e211c11ca8a7068bb9fbe6f17034dcc5"
      url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ee76116436f388ffd5d7b7efcc4e9e77c7bb50f1a114ed9f83052d0d9a00e427"
      url "https://github.com/cerberauth/openapi-oathkeeper/releases/download/v#{version}/openapi-oathkeeper_Linux_arm64.tar.gz"
    end
  end

  name "openapi-oathkeeper"
  desc "Generate Ory Oathkeeper access rules from an OpenAPI 3 contract."
  homepage "https://github.com/cerberauth/openapi-oathkeeper"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-oathkeeper"

  # No zap stanza required

end
