# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxyaudit" do
  version "0.2.0"

  on_macos do
    sha256 "bdcca33392e9952ea3ece952c094863d5cca0c54557b10c1c75e4e61eba59920"
    url "https://github.com/cerberauth/proxyaudit/releases/download/v#{version}/proxyaudit_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "53ffb847e414a78e8c6adc3847df4f16b5f9eeec20124f3fd49cf19bac3c9cb0"
      url "https://github.com/cerberauth/proxyaudit/releases/download/v#{version}/proxyaudit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a2e4e8a44ce50d0fef4bee592f944b3f74bcea6780f1dfa449e0b8d43b777c5f"
      url "https://github.com/cerberauth/proxyaudit/releases/download/v#{version}/proxyaudit_Linux_x86_64.tar.gz"
    end
  end

  name "proxyaudit"
  desc "Reverse proxy / API gateway security scanner — TLS, HTTP security headers, header trust boundaries, and exposed management interfaces."
  homepage "https://github.com/cerberauth/proxyaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxyaudit"

  # No zap stanza required
end
