# This file was generated by GoReleaser. DO NOT EDIT.
cask "proxyaudit" do
  version "0.1.0"

  on_macos do
    sha256 "3d652bad0d663cfa3d8479e264d8bf4063ab6d868ae472025eaeb1219e8399bd"
    url "https://github.com/cerberauth/proxyaudit/releases/download/v#{version}/proxyaudit_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "456a5b22778dcf36bd510c35d8de13c8796dbe391058c23e8317d72922dfc919"
      url "https://github.com/cerberauth/proxyaudit/releases/download/v#{version}/proxyaudit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ea630d11a57d33c7a21b23b508f48442b419d9513ab94e271b4179047cc41cbc"
      url "https://github.com/cerberauth/proxyaudit/releases/download/v#{version}/proxyaudit_Linux_x86_64.tar.gz"
    end
  end

  name "proxyaudit"
  desc "Reverse proxy / API gateway security scanner — TLS, HTTP security headers, header trust boundaries, and exposed management interfaces."
  homepage "https://github.com/cerberauth/proxyaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "proxyaudit"

  # No zap stanza required
end
