# This file was generated by GoReleaser. DO NOT EDIT.
cask "stubidp" do
  name "stubidp"
  desc "A mock OpenID Connect server for developers. Zero config, instant OIDC."
  homepage "https://github.com/cerberauth/stubidp"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stubidp"

  on_macos do
    on_intel do
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Darwin_x86_64.tar.gz"
      sha256 "782282a7aebd13b42acba8ccdecadf578531dd03dabfcee781b15a4c3606d3b9"
    end
    on_arm do
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Darwin_arm64.tar.gz"
      sha256 "15d63b3886945426df3912188c470a04f581225f9a884d7d4777a7fbe416e890"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Linux_x86_64.tar.gz"
      sha256 "d558681bd15626b92370c4948cf57b020546dd94ed1405b2442885d42e28ea6b"
    end
    on_arm do
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Linux_arm64.tar.gz"
      sha256 "2a43f863602f8b66922339567a44082429f9b4b9ee3c002327d0b36bb9a2b28b"
    end
  end

  # No zap stanza required
end
