# This file was generated by GoReleaser. DO NOT EDIT.
cask "stubidp" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "ad8a84b155d0f3bfbf1bcdf45f165b45408391e9a77e968dc0cf5c269050b5b2"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b9b995e6d2c50a8416433feb37c3fb54d1724d5e465b34f869a1dd57284502d0"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "feaece0d08708f9fe3a12ddb8328a7dff189782fbfc522e34e5e199dec5d2d0c"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "22e93e1392993a6afb21fa667045047a68013f6bb8cd6a8352ea5df97e926c6b"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Linux_arm64.tar.gz"
    end
  end

  name "stubidp"
  desc "A mock OpenID Connect server for developers. Zero config, instant OIDC."
  homepage "https://www.cerberauth.com/docs/stubidp/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stubidp"

  # No zap stanza required

end
