# This file was generated by GoReleaser. DO NOT EDIT.
cask "stubidp" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "675581730f08dd208c6fc0607700124cba8101a802c122ac35b079f2926b64e8"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4dd8ba852a4db55a2060c19adbd5f84da0705e0532c45f1e6dbd50b2d2a90df8"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5bd254e732bb47c819f74e562bfac24b8d8ba5904696fc876fd482d14e512356"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4f0df4fb283ed5e78624e86f65ffee881e08d24c14631781bdb5f1b5945c7a7c"
      url "https://github.com/cerberauth/stubidp/releases/download/v#{version}/stubidp_Linux_arm64.tar.gz"
    end
  end

  name "stubidp"
  desc "A mock OpenID Connect server for developers. Zero config, instant OIDC."
  homepage "https://www.cerberauth.com/docs/stubidp/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stubidp"

  # No zap stanza required

end
