# This file was generated by GoReleaser. DO NOT EDIT.
cask "vulnapi" do
  version "0.10.0"

  on_macos do
    sha256 "695761722946d6ca2ade28d1b0f8f58ffd70e327c427bcb4c1e598fc48db9431"
    url "https://github.com/cerberauth/vulnapi/releases/download/v#{version}/vulnapi_Darwin_all.tar.gz"
  end
  on_linux do
    on_arm do
      sha256 "6da74260324e745e2ebdb8b0a3d5a753ddc61befc3f644a6e4a41b78d5b29dbd"
      url "https://github.com/cerberauth/vulnapi/releases/download/v#{version}/vulnapi_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1ad2ac57de912d4274ebd13f966df4d2b16dda1339f07f40be379582d52a44ef"
      url "https://github.com/cerberauth/vulnapi/releases/download/v#{version}/vulnapi_Linux_x86_64.tar.gz"
    end
  end

  name "vulnapi"
  desc "Scan your APIs for security vulnerabilities and weaknesses."
  homepage "https://github.com/cerberauth/vulnapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vulnapi"

  # No zap stanza required
end
