# This file was generated by GoReleaser. DO NOT EDIT.
cask "vulnapi" do
  version "0.9.0"

  on_macos do
    url "https://github.com/cerberauth/vulnapi/releases/download/v#{version}/vulnapi_Darwin_all.tar.gz"
    sha256 "b28bf8a4e4d85a9a3bdc6e69d80ca7598219a5d356f9c2ea7b0035999e8bcb6f"
  end

  on_linux do
    on_intel do
      url "https://github.com/cerberauth/vulnapi/releases/download/v#{version}/vulnapi_Linux_x86_64.tar.gz"
      sha256 "ecbba17c9e6860be81dab3b4955103176b06a38026007ccf3af964660c998f4e"
    end
    on_arm do
      url "https://github.com/cerberauth/vulnapi/releases/download/v#{version}/vulnapi_Linux_arm64.tar.gz"
      sha256 "3d897018367291ec12a4c6c43a92a80feb190514b1fb23c0a4ecf762acae7442"
    end
  end

  name "vulnapi"
  desc "Scan your APIs for security vulnerabilities and weaknesses."
  homepage "https://github.com/cerberauth/vulnapi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vulnapi"

  # No zap stanza required

end
